allowBuilds:
  "@clerk/shared": true
  "@prisma/engines": true
  bufferutil: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

overrides:
  "@aws-sdk/client-s3": "3.1127.0"
